version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    groups:
      react-packages:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      react-router-packages:
        patterns:
          - "react-router"
          - "@react-router/*"
      vitest-packages:
        patterns:
          - "vitest"
          - "@vitest/*"

