import type { BFFDataRecord } from '@/types/record';

const createFakeRecord = (
  title: string,
  firstName: string,
  lastName: string,
  year: string,
  mine: boolean,
  readyForReview: boolean,
): BFFDataRecord => {
  return {
    id: `diva-output:${Date.now()}`,
    recordType: 'diva-output',
    validationType: 'publication_report',
    createdAt: '2025-03-03T14:15:22.123456Z',
    createdBy: '161616',
    data: {
      mine,
      readyForReview,
      output: {
        recordInfo: {
          validationType: { value: 'publication_report' },
          dataDivider: { value: 'divaData' },
          recordContentSource: { value: 'kth' },
          genre_type_outputType: {
            value: 'publication_report',
            _type: 'outputType',
          },
          id: { value: `diva-output:${Date.now()}` },
          type: { value: 'diva-output' },
          createdBy: { value: '161616' },
          tsCreated: { value: '2025-03-03T22:00:00.753951Z' },
          updated: [
            {
              tsUpdated: { value: '2025-03-03T22:00:00.753951Z' },
              updatedBy: { value: '161616' },
            },
          ],
        },
        language: [
          {
            'languageTerm_authority_iso639-2b_type_code': {
              value: 'swe',
              _authority: 'iso639-2b',
              _type: 'code',
            },
          },
        ],
        genre_type_contentType: {
          value: 'ref',
          _type: 'contentType',
        },
        titleInfo: {
          title: {
            value: title,
          },
          _lang: 'swe',
        },
        originInfo: {
          dateIssued: { year: { value: year } },
        },
        admin: { reviewed: { value: 'true' } },
        adminInfo: { visibility: { value: 'published' } },
        name_type_personal: [
          {
            namePart_type_given: [
              {
                value: firstName,
                _type: 'given',
              },
            ],
            namePart_type_family: [
              {
                value: lastName,
                _type: 'family',
              },
            ],
            _type: 'personal',
          },
        ],
      },
    },
  };
};

export const fakeRecords = [
  createFakeRecord(
    'A comparison between particle characteristics between two railway brake pads',
    'Saeed',
    'Abbasi',
    '2025',
    false,
    true,
  ),
  createFakeRecord(
    'Quantum Computing: Advancements and Challenges',
    'Per',
    'Persson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'The Impact of Artificial Intelligence on Modern Healthcare',
    'Emma',
    'Johnson',
    '2025',
    false,
    true,
  ),
  createFakeRecord(
    'Sustainable Energy Solutions for Urban Development',
    'Michael',
    'Chen',
    '2023',
    false,
    false,
  ),
  createFakeRecord(
    'Neuroplasticity and Its Role in Learning',
    'Per',
    'Persson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'Climate Change: Mitigation Strategies for Coastal Cities',
    'Sophia',
    'Rodriguez',
    '2025',
    true,
    false,
  ),
  createFakeRecord(
    'The Future of Autonomous Vehicles',
    'Per',
    'Persson',
    '2023',
    false,
    false,
  ),
  createFakeRecord(
    'Advancements in CRISPR Gene Editing Technology',
    'David',
    'Kim',
    '2024',
    false,
    true,
  ),
  createFakeRecord(
    'Cybersecurity in the Age of IoT',
    'Per',
    'Persson',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'The Role of Gut Microbiome in Mental Health',
    'Sophia',
    'Rodriguez',
    '2023',
    true,
    false,
  ),
  createFakeRecord(
    'Renewable Energy: Innovations in Solar Cell Efficiency',
    'Per',
    'Persson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'The Psychology of Decision Making in Financial Markets',
    'Ethan',
    'Brown',
    '2025',
    false,
    true,
  ),
  createFakeRecord(
    'Nanotechnology in Cancer Treatment',
    'Per',
    'Persson',
    '2023',
    false,
    false,
  ),
  createFakeRecord(
    'The Impact of Social Media on Political Discourse',
    'Ava',
    'Wilson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'Artificial Neural Networks in Weather Prediction',
    'Per',
    'Persson',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'Sustainable Agriculture: Vertical Farming Technologies',
    'Noah',
    'Garcia',
    '2023',
    false,
    true,
  ),
  createFakeRecord(
    'The Ethics of AI in Criminal Justice Systems',
    'Per',
    'Persson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'Advancements in Fusion Energy Research',
    'Isabella',
    'Martinez',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'The Role of Epigenetics in Aging',
    'Per',
    'Persson',
    '2023',
    false,
    false,
  ),
  createFakeRecord(
    'Quantum Cryptography: Ensuring Future Data Security',
    'Liam',
    'Anderson',
    '2024',
    false,
    true,
  ),
  createFakeRecord(
    'The Neuroscience of Creativity',
    'Per',
    'Persson',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'Sustainable Urban Planning: The 15-Minute City Concept',
    'Sophia',
    'Rodriguez',
    '2023',
    true,
    false,
  ),
  createFakeRecord(
    'Advancements in 3D Bioprinting for Organ Transplantation',
    'Per',
    'Persson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'The Impact of Remote Work on Urban Development',
    'James',
    'Lee',
    '2025',
    false,
    true,
  ),
  createFakeRecord(
    'Machine Learning in Drug Discovery',
    'Per',
    'Persson',
    '2023',
    false,
    false,
  ),
  createFakeRecord(
    'The Role of Dark Matter in Universe Formation',
    'Charlotte',
    'White',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'Sustainable Fashion: Innovations in Eco-friendly Textiles',
    'Per',
    'Persson',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'The Psychology of Conspiracy Theories in the Digital Age',
    'Benjamin',
    'Harris',
    '2023',
    false,
    true,
  ),
  createFakeRecord(
    'Advancements in Quantum Sensing Technologies',
    'Per',
    'Persson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'The Impact of Microplastics on Marine Ecosystems',
    'Amelia',
    'Clark',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'Artificial Intelligence in Music Composition',
    'Per',
    'Persson',
    '2023',
    false,
    false,
  ),
  createFakeRecord(
    'The Future of Space Tourism',
    'William',
    'Lewis',
    '2024',
    false,
    true,
  ),
  createFakeRecord(
    'Neuromorphic Computing: Mimicking Brain Functions',
    'Per',
    'Persson',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'Sustainable Water Management in Arid Regions',
    'Sophia',
    'Rodriguez',
    '2023',
    true,
    false,
  ),
  createFakeRecord(
    'The Role of Blockchain in Supply Chain Transparency',
    'Per',
    'Persson',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'Advancements in Photonic Quantum Computing',
    'Daniel',
    'Young',
    '2025',
    false,
    true,
  ),
  createFakeRecord(
    'The Impact of Virtual Reality on Education',
    'Per',
    'Persson',
    '2023',
    false,
    false,
  ),
  createFakeRecord(
    'Sustainable Aviation: Electric and Hydrogen-Powered Aircraft',
    'Emily',
    'Walker',
    '2024',
    false,
    false,
  ),
  createFakeRecord(
    'The Neurobiology of Addiction',
    'Per',
    'Persson',
    '2025',
    false,
    false,
  ),
  createFakeRecord(
    'Artificial Intelligence in Climate Modeling',
    'Alexander',
    'King',
    '2023',
    false,
    true,
  ),
  createFakeRecord(
    'The Future of Personalized Medicine',
    'Per',
    'Persson',
    '2024',
    false,
    true,
  ),
  createFakeRecord(
    'Advancements in Carbon Capture and Storage Technologies',
    'Sophia',
    'Rodriguez',
    '2025',
    true,
    true,
  ),
];
